# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test42SearchingPeoplePositiveResults():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_42SearchingPeoplePositiveResults(self):
    self.driver.get("https://x.com/home")
    self.driver.set_window_size(652, 726)
    element = self.driver.find_element(By.CSS_SELECTOR, ".r-45ll9u > .r-o7ynqc")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-175oi2r:nth-child(2) > .css-175oi2r > .css-175oi2r > .r-4qtqp9 path")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".css-175oi2r:nth-child(2) > .css-175oi2r > .css-175oi2r:nth-child(2) > .css-175oi2r > .css-175oi2r > .r-4qtqp9 path").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-175oi2r:nth-child(2) > .css-175oi2r > .css-175oi2r > .r-4qtqp9 path")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".r-30o5oe").click()
    self.driver.find_element(By.CSS_SELECTOR, ".r-30o5oe").send_keys("Alfamart")
    self.driver.find_element(By.CSS_SELECTOR, ".r-30o5oe").send_keys(Keys.ENTER)
  
